logging-path: ./logs/
cndRoot: //oss-erp2.xmhougu.com/hougu-bi

server:
  port: 38181
  servlet:
    context-path:
    session:
      timeout: 7d

spring:
  application:
    name: hougu-bi
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/enjoy_admin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 960720
    database: enjoy_admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    maximum-pool-size: 10
    max-lifetime: 30000
    idle-timeout: 30000
  redis:
    database: 12
    host: 127.0.0.1
    port: 6379
    password:
  thymeleaf:
    cache: false  #开发阶段，建议关闭thymeleaf的缓存
    mode: HTML # LEGACYHTML5 / HTML

